# Generated by Django 5.0.6 on 2024-06-28 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_customer_price_stri_price_id_product_stri_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stri_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
