# Generated by Django 5.0.6 on 2024-06-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stri_subscription_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
