# Generated by Django 5.0.6 on 2024-06-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_subscription_stri_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='stri_customer_id',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='price',
            name='stri_price_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
