# Generated by Django 5.0.6 on 2024-06-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_customer_stri_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stri_product_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stri_subscription_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
