# Generated by Django 5.0.6 on 2024-06-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_product_stri_product_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product table',
        ),
    ]
