# Generated by Django 5.0.6 on 2024-07-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='interval',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=20),
        ),
        migrations.AddField(
            model_name='price',
            name='interval_count',
            field=models.IntegerField(default=1),
        ),
    ]
