# Generated by Django 5.0.6 on 2024-07-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_price_interval_price_interval_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stri_subscription_id',
            new_name='stri_customer_id',
        ),
    ]
