# Generated by Django 5.1 on 2024-08-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_rename_stri_subscription_id_subscription_stri_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invoice_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_url',
            field=models.URLField(editable=False, null=True),
        ),
    ]
