# Generated by Django 5.1 on 2024-08-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_customer_invoice_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stri_customer_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='invoice_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stri_subscription_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
