# Generated by Django 5.1 on 2024-08-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_subscription_stri_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='invoice_url',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stri_subscription_id',
        ),
    ]
