# Generated by Django 5.1 on 2024-08-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_subscription_invoice_id_subscription_invoice_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='invoice_url',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stri_subscription_id',
        ),
    ]
