# Generated by Django 5.1 on 2024-08-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_subscription_stri_subscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='invoice_url',
        ),
    ]
