# Generated by Django 5.1 on 2024-08-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_remove_customer_invoice_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='invoice_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
